---

- name: Format BeeGFS storage block device
  filesystem:
    dev: "{{ beegfs_storage_block_dev }}"
    fstype: ext4
    opts: "-m 0 -L beegfs-data"

- name: Mount BeeGFS data volume
  mount:
    path: "{{ beegfs_storage_dir }}"
    src: "{{ beegfs_storage_block_dev }}"
    fstype: ext4
    opts: "{{ beegfs_mount_opts }}"
    state: mounted
