---

- name: Install beegfs-mgmtd package
  package:
    name: beegfs-mgmtd
  tags:
    - beegfs
    - beegfs-mgmtd

- name: "Ensure {{ beegfs_mgmtd_dir }} exists"
  file:
    path: "{{ beegfs_mgmtd_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - beegfs
    - beegfs-mgmtd

- name: Install beegfs-mgmtd.conf template
  template:
    src: beegfs-mgmtd.conf.j2
    dest: /etc/beegfs/beegfs-mgmtd.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - beegfs
    - beegfs-mgmtd

- name: Enable and start the beegfs-mgmtd service
  systemd:
    name: beegfs-mgmtd
    daemon_reload: yes
    enabled: yes
    state: started
  tags:
    - beegfs
    - beegfs-mgmtd
