#! /bin/bash

# (c) Thomas Lange, 2001-2012, lange@debian.org

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

sed -i "s/net.ipv4.tcp_congestion_control.*$/net.ipv4.tcp_congestion_control=dctcp/" $target/etc/sysctl.conf
sed -i "s/#kernel.unprivileged_bpf_disabled/kernel.unprivileged_bpf_disabled/" $target/etc/sysctl.conf
#$ROOTCMD wget https://ftp2.cn.debian.org/debian/pool/main/g/gradm2/gradm2_3.1~201701031918-2_amd64.deb
#for offline installation
fcopy /pkg/gradm2_3.1~201701031918-2_amd64.deb
$ROOTCMD dpkg -i /pkg/gradm2_3.1~201701031918-2_amd64.deb
$ROOTCMD rm -r /pkg

exit $error
