#! /bin/bash

fcopy -iM /etc/docker/daemon.json
sed -i 's/^net.ipv4.ip_forward.*$/net.ipv4.ip_forward=1/' $target/etc/sysctl.conf
ifclass PXECENTOS && $ROOTCMD ln -sf /usr/lib/systemd/system/docker.service /etc/systemd/system/multi-user.target.wants/docker.service

exit $error
