#! /bin/bash

# (c) Michael Goetze, 2010-11, mgoetze@mgoetze.net
# Thomas Lange, 2015

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

$ROOTCMD yum remove -y kernel-tools kernel-tools-libs

$ROOTCMD yum install -y kernel-ml kernel-ml-devel kernel-ml-headers kernel-ml-tools

exit $error
