#! /bin/bash

$ROOTCMD yum clean all
$ROOTCMD yum remove -y biosdevname
$ROOTCMD yum remove -y NetworkManager NetworkManager-libnm
$ROOTCMD yum remove -y iwl*
$ROOTCMD yum remove -y polkit aic94xx-firmware ivtv-firmware dnsmasq
$ROOTCMD yum remove -y plymouth plymouth-core-libs
$ROOTCMD yum remove -y gssproxy
#$ROOTCMD yum remove -y kexec-tools irqbalance
$ROOTCMD yum remove -y ppp wpa_supplicant alsa-lib avahi-libs tuned

