---

beegfs_apt_key: https://www.beegfs.io/release/latest-stable/gpg/DEB-GPG-KEY-beegfs
beegfs_repo_data: "deb [arch=amd64] http://www.beegfs.io/release/beegfs_7 deb9 non-free"

# Distribution-specific parameters
beegfs_distro_vars:
  RedHat:
    beegfs_repo_url: "https://www.beegfs.io/release/latest-stable/dists/beegfs-rhel7.repo"
    beegfs_repo_key: "https://www.beegfs.io/release/latest-stable/gpg/RPM-GPG-KEY-beegfs"
    beegfs_repo_file: "/etc/yum.repos.d/beegfs-rhel7.repo"
    kernel_dev_pkg: "kernel-ml-devel"
    rdma_dev_pkgs:
      - "librdmacm"
      - "libibmad"
      - "libibumad"
      - "rdma-core"
      - "libibverbs"
      - "libibverbs-utils"
      - "libbeegfs-ib"

  Debian:
    beegfs_repo_url: "https://www.beegfs.io/release/latest-stable/dists/beegfs-deb9.list"
    beegfs_repo_key: "https://www.beegfs.io/release/latest-stable/gpg/DEB-GPG-KEY-beegfs"
    beegfs_repo_file: "/etc/apt/sources.list.d/beegfs_deb9.list"
    kernel_dev_pkg: "linux-headers"
    rdma_dev_pkgs:
      - "librdmacm-dev"
      - "libibmad-dev"
      - "libibumad-dev"
      - "libibverbs-dev"
      - "libbeegfs-ib"

# BeeGFS repo
beegfs_add_repos: true
beegfs_repo_url: "{{ beegfs_distro_vars[ansible_os_family]['beegfs_repo_url'] }}"
beegfs_repo_key: "{{ beegfs_distro_vars[ansible_os_family]['beegfs_repo_key'] }}"
beegfs_repo_file: "{{ beegfs_distro_vars[ansible_os_family]['beegfs_repo_file'] }}"
