#! /bin/bash

# (c) Michael Goetze, 2010-11, mgoetze@mgoetze.net
# Thomas Lange, 2015

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

if ifclass CUDA ; then
    $ROOTCMD apt-get install -y -t stretch-backports nvidia-driver nvidia-smi
fi

exit $error
