#! /bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

mount -o bind /dev $target/dev
#https://github.com/firehol/netdata
$ROOTCMD bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh) --dont-wait --dont-start-it
umount $target/dev
$ROOTCMD cp /opt/netdata/system/netdata-init-d /etc/init.d/netdata
chmod +x $target/etc/init.d/netdata
$ROOTCMD chkconfig --add netdata

cat <<'EOF' > $target/opt/netdata/etc/netdata/netdata.conf
[global]
        history = 86400
[web]
        # default port = 19999
        # bind to = *
EOF

#sed -i /^DEFAULT_RECIPIENT_EMAIL/s/root/user@mail.com/ $target/opt/netdata/etc/netdata/health_alarm_notify.conf
[ -n "$IPADDR" ] && sed -i "s/^.*bind\ to\ =\ \*$/\        bind\ to\ =\ $IPADDR/" $target/opt/netdata/etc/netdata/netdata.conf 

exit $error
