---
- name: Add BeeGFS repos is beegfs_add_repos is true
  block:

  - name: Ensure the BeeGFS package repo is defined
    get_url:
      url: "{{ beegfs_repo_url }}"
      dest: "{{ beegfs_repo_file }}"
    become: true

  - name: Load package repo key
    block:
      - name: add apt key for debian family machines
        apt_key:
          state: present
          url: "{{ beegfs_repo_key }}"
        when: ansible_os_family == "Debian"
      - name: add rpm key for redhat family machines
        rpm_key:
          state: present
          key: "{{ beegfs_repo_key }}"
        when: ansible_os_family == "RedHat"
    become: true

  - name: Refresh apt repos and install https repo support for Debian
    apt:
      name:
        - base-files
        - apt-transport-https
      state: present
      update_cache: true
    become: true
    when: ansible_os_family == "Debian"

  when: beegfs_add_repos | bool


#- name: Install BeeGFS public key
#  apt_key:
#    url: "{{ beegfs_apt_key }}"
#    state: present
#  tags:
#    - beegfs
#    - beegfs-repos
#
#- name: Install BeeGFS repo
#  apt_repository:
#    repo: "{{ beegfs_repo_data }}"
#    state: present
#    filename: 'beegfs'
#  tags:
#    - beegfs
#    - beegfs-repos
