#! /bin/bash

# (c) Thomas Lange, 2001-2012, lange@debian.org

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code
#sshd listen internal nic only
[ -n "$IPADDR" ] && sed -i s/#ListenAddress\ 0.0.0.0/ListenAddress\ $IPADDR/ $target/etc/ssh/sshd_config




exit $error
