#! /bin/bash

#ubuntu 14.04 disk queue patch
sed -i '/write_cache/d' $target/etc/sysfs.conf

[ -n "$DEFAULTLOCALE" ] && ainsl -a /etc/locale.gen 'en_US.UTF-8 UTF-8'
[ -n "$DEFAULTLOCALE" ] && ainsl -a /etc/default/locale LANG="$DEFAULTLOCALE"
$ROOTCMD locale-gen
