#! /bin/bash

#sed -i 's/-L debian_banner_2/-L ubuntu/' $target/etc/linux_logo.conf
[ -n "$DEFAULTLOCALE" ] && ainsl -a /etc/locale.gen 'en_US.UTF-8 UTF-8'
[ -n "$DEFAULTLOCALE" ] && ainsl -a /etc/default/locale LANG="$DEFAULTLOCALE"
$ROOTCMD locale-gen
