#! /bin/bash

# (c) Thomas Lange, 2001-2012, lange@debian.org

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

touch $target/var/log/php_errors.log
$ROOTCMD chown www-data:www-data /var/log/php_errors.log
chmod 0600 $target/var/log/php_errors.log

exit $error
