#! /bin/bash

# (c) Thomas Lange, 2001-2012, lange@debian.org

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code
#prepare hostname
ainsl /etc/hosts "$IPADDR $HOSTNAME.$DOMAIN $HOSTNAME pvelocalhost"
sed -i /shm/d $target/etc/fstab
sed -i /hidepid/d $target/etc/fstab
unlink  $target/etc/systemd/system/multi-user.target.wants/auditd.service 
unlink  $target/etc/systemd/system/multi-user.target.wants/netfilter-persistent.service
unlink  $target/etc/sysctl.d/99-sysctl.conf
rm $target/etc/sysctl.conf

exit $error
